### ISSUE TITLE
Umbraco 11+

### ISSUE THREAD

**Issue by lundmorten** [madsoulswe/Our.Umbraco.Honeypot#13]
Hi madsoulswe
Thank you for creating this package. On marketplace.umbraco.com it says it works on Umbraco 12. But currently it only works for Umbraco versions up to 11. Is there any plan to make it work on Umbraco 11+? :)

Unfortunately, I don't have the skills to help contribute to the project.

**Comment by madsoulswe** [comment]
Hi!

I made a .net 7 release that targets Umbraco v11 and v12.

https://github.com/madsoulswe/Our.Umbraco.Honeypot/releases/tag/release%2F1.2.0

https://www.nuget.org/packages/Our.Umbraco.Honeypot/


Thanks for the other Readme PR!
