### ISSUE TITLE
Umbraco 13 support

### ISSUE THREAD

**Issue by Laantje** [madsoulswe/Our.Umbraco.Honeypot#16]
Hi :)

Thanks for the awesome package!
Unfortunately, it does not yet support Umbraco 13, which has been released last month.

Support for the latest versions would be appreciated!

**Comment by madsoulswe** [comment]
@Laantje Hello! v13 should be working now.

**Comment by Laantje** [comment]
> @Laantje Hello! v13 should be working now.

Hi, thanks a lot!
Very much appreciated! :)
