### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by jonas-jaderberg** [madsoulswe/Our.Umbraco.Honeypot#9]
Hi,
I tried this on Umbraco 11.2 and Umbraco Forms 11.03.
Installed fine but when when tied to add the field to a form it gaves a 404 error missing file \App_Plugins\Our.Umbraco.Honeypot\FieldTypes\Honeypot.html
In Visual Studio I can see the file but it looks like a link to the file in the package.

I solved it by coping the file from the package.

Same for file \Views\Partials\Forms\Themes\default\FieldTypes\FieldType.Honeypot.cshtml

After that it seams to be working

**Comment by madsoulswe** [comment]
Thanks!

Not sure how I have not notice this 😅

**Comment by madsoulswe** [comment]
Fixed in: https://github.com/madsoulswe/Our.Umbraco.Honeypot/releases/tag/release%2F1.1.4

**Comment by jonas-jaderberg** [comment]
Can confirm that 1.1.4 fixed the issue
